# Generated by Django 4.2.19 on 2025-03-23 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hikit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True, related_name="past_routes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="routes/"),
        ),
        migrations.AddField(
            model_name="route",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True, related_name="saved_routes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
