# Generated by Django 4.2.19 on 2025-03-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hikit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Upload a square image (recommended 400x400px)",
                null=True,
                upload_to="profile_pics",
                verbose_name="Profile Photo",
            ),
        ),
    ]
